### PR TITLE
Nested method access

### PR DESCRIPTION
**Pull request by mateomurphy**
Hi, I was working with your API, and I was a little annoyed at having to do: 

`photo.user['links']['html']`

So I've replaced `OpenStruct` with `Hashie::Mash` so that I can do:

`photo.user.links.html`

I added a single spec to make sure it works, let me know if you'd like more

### CODE REVIEW

**Comment by aaronklaassen** [comment]
Hey @mateomurphy.  I'd rather not add the hashie dependency, because with `OpenStruct` you can already use that syntax. You're right though that the `photo.user.links` does currently return a `Hash` not an `OpenStruct` - is that what was bothering you?

**Comment by mateomurphy** [comment]
Yes exactly. Hashie is a pretty heavy library for this use, but it was also the simplest. I can update the PR to remove the dependency if you'd like?

**Comment by adimasuhid** [comment]
Ruby 2.3.x's `dig` functionality might normalize the issue for you. Something like:

```
photo.dig(:user, :links, :html)
```

Would work for both `OpenStruct` and `Hash` without requiring change for the unsplash api.

**Comment by mateomurphy** [comment]
I found a much simpler solution (one line of code)

I think it's more elegant that the API consistently returns objects rather than objects some times and hashes in others, and having to work around that!

**Comment by aaronklaassen** [comment]
@mateomurphy Works for me. Thanks for the PR.

**Pull request merged**
