### PR TITLE
Add parameter per_page to search

### PR DESCRIPTION
**Pull request by MatthiasWinkelmann**
``` Unsplash::Photo.search('dogs', 1, 30)```

### CODE REVIEW

**Comment by MatthiasWinkelmann** [comment]
Note that the CI failed because the response to the new test isn't cached.

**Comment by gustavosobral** [comment]
Hello guys from Unsplash! First of all, thanks for the awesome Unsplash services.

Is there any news about this PR? I was seeking exactly for this `per_page` param on search method. This param will decrease my rate usage by 3. Otherwise, I will be forced to build another Ruby wrapper around the Unsplash RESTful API :disappointed: 

Please maintainers, consider this PR when possible.

**Comment by lukechesser** [comment]
@aaronklaassen do you know if we have any blockers on merging this?

**Comment by aaronklaassen** [comment]
@lukechesser I need to fix the tests. I can do it shortly and can include it in the next release this week.

**Comment by aaronklaassen** [comment]
Actually sorry I'm just going to close this; it's a subset of what was fixed in #36. I'll finally get on a PR to make the tests point away from localhost, though. Thanks @MatthiasWinkelmann

**Pull request closed without merging**
