### PR TITLE
Add (coveralls) coverage badge

### PR DESCRIPTION
**Pull request by mth4saurabh**
PR for Issue #13 

1. Use coveralls for adding badge
2. Update rvm version for travis-ci

P.S. - You will need to add this repo to [coveralls](https://coveralls.io/)

### CODE REVIEW

**Comment by lukechesser** [comment]
Thanks @mth4saurabh gonna switch this over to Travis and then pull this in

**Comment by mth4saurabh** [comment]
hi @lukechesser , any updates on this? also I was wondering if I can get a reply from `ruby@unsplash.com` :smiley:

**Comment by aaronklaassen** [comment]
@mth4saurabh I just moved this project over from Codeship to Travis (in #24). Would you mind updating this PR?

**Comment by mth4saurabh** [comment]
@aaronklaassen : Done!

**Comment by aaronklaassen** [comment]
Awesome thank you!

**Pull request merged**
